/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root"
import { Route as IndexRouteImport } from "./app/index"
import { Route as NewIndexRouteImport } from "./app/new/index"
import { Route as CbvCbvIdIndexRouteImport } from "./app/cbv/$cbvId/index"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const NewIndexRoute = NewIndexRouteImport.update({
  id: "/new/",
  path: "/new/",
  getParentRoute: () => rootRouteImport,
} as any)
const CbvCbvIdIndexRoute = CbvCbvIdIndexRouteImport.update({
  id: "/cbv/$cbvId/",
  path: "/cbv/$cbvId/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/new/": typeof NewIndexRoute
  "/cbv/$cbvId/": typeof CbvCbvIdIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/new": typeof NewIndexRoute
  "/cbv/$cbvId": typeof CbvCbvIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/new/": typeof NewIndexRoute
  "/cbv/$cbvId/": typeof CbvCbvIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/new/" | "/cbv/$cbvId/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/new" | "/cbv/$cbvId"
  id: "__root__" | "/" | "/new/" | "/cbv/$cbvId/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewIndexRoute: typeof NewIndexRoute
  CbvCbvIdIndexRoute: typeof CbvCbvIdIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/new/": {
      id: "/new/"
      path: "/new"
      fullPath: "/new/"
      preLoaderRoute: typeof NewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/cbv/$cbvId/": {
      id: "/cbv/$cbvId/"
      path: "/cbv/$cbvId"
      fullPath: "/cbv/$cbvId/"
      preLoaderRoute: typeof CbvCbvIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewIndexRoute: NewIndexRoute,
  CbvCbvIdIndexRoute: CbvCbvIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
