/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root"
import { Route as UnauthorizedRouteImport } from "./app/unauthorized"
import { Route as DeskLayoutRouteImport } from "./app/desk/layout"
import { Route as DashboardLayoutRouteImport } from "./app/dashboard/layout"
import { Route as AuthLayoutRouteImport } from "./app/_auth/layout"
import { Route as IndexRouteImport } from "./app/index"
import { Route as WorkflowIndexRouteImport } from "./app/workflow/index"
import { Route as DeskIndexRouteImport } from "./app/desk/index"
import { Route as DashboardIndexRouteImport } from "./app/dashboard/index"
import { Route as AcceptInvitationIndexRouteImport } from "./app/accept-invitation/index"
import { Route as AuthResetPasswordRouteImport } from "./app/_auth/reset-password"
import { Route as AuthRegisterRouteImport } from "./app/_auth/register"
import { Route as AuthLoginRouteImport } from "./app/_auth/login"
import { Route as AuthForgotPasswordRouteImport } from "./app/_auth/forgot-password"
import { Route as DeskTradeLayoutRouteImport } from "./app/desk/trade/layout"
import { Route as DeskSettingsLayoutRouteImport } from "./app/desk/settings/layout"
import { Route as DeskPeopleLayoutRouteImport } from "./app/desk/people/layout"
import { Route as DeskBankingLayoutRouteImport } from "./app/desk/banking/layout"
import { Route as DeskAccountingLayoutRouteImport } from "./app/desk/accounting/layout"
import { Route as DashboardSuperAdminLayoutRouteImport } from "./app/dashboard/super-admin/layout"
import { Route as DashboardSettingsLayoutRouteImport } from "./app/dashboard/settings/layout"
import { Route as DeskTradeIndexRouteImport } from "./app/desk/trade/index"
import { Route as DeskSettingsIndexRouteImport } from "./app/desk/settings/index"
import { Route as DeskPeopleIndexRouteImport } from "./app/desk/people/index"
import { Route as DeskBankingIndexRouteImport } from "./app/desk/banking/index"
import { Route as DeskAccountingIndexRouteImport } from "./app/desk/accounting/index"
import { Route as DashboardSuperAdminIndexRouteImport } from "./app/dashboard/super-admin/index"
import { Route as DashboardSettingsIndexRouteImport } from "./app/dashboard/settings/index"
import { Route as DeskSettingsTaxesRouteImport } from "./app/desk/settings/taxes"
import { Route as DeskSettingsRolesRouteImport } from "./app/desk/settings/roles"
import { Route as DeskSettingsCalendarRouteImport } from "./app/desk/settings/calendar"
import { Route as DeskPeopleEmployeesRouteImport } from "./app/desk/people/employees"
import { Route as DashboardSettingsSecurityRouteImport } from "./app/dashboard/settings/security"
import { Route as ApiRpcSplatRouteImport } from "./app/api/rpc.$"
import { Route as ApiAuthSplatRouteImport } from "./app/api/auth.$"
import { Route as DeskTradeSalesIndexRouteImport } from "./app/desk/trade/sales/index"
import { Route as DeskSettingsLocationsIndexRouteImport } from "./app/desk/settings/locations/index"
import { Route as DeskPeopleSuppliersIndexRouteImport } from "./app/desk/people/suppliers/index"
import { Route as DashboardSuperAdminUsersIndexRouteImport } from "./app/dashboard/super-admin/users/index"
import { Route as DashboardSuperAdminTestEmailIndexRouteImport } from "./app/dashboard/super-admin/test-email/index"

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: "/unauthorized",
  path: "/unauthorized",
  getParentRoute: () => rootRouteImport,
} as any)
const DeskLayoutRoute = DeskLayoutRouteImport.update({
  id: "/desk",
  path: "/desk",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowIndexRoute = WorkflowIndexRouteImport.update({
  id: "/workflow/",
  path: "/workflow/",
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DeskLayoutRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const AcceptInvitationIndexRoute = AcceptInvitationIndexRouteImport.update({
  id: "/accept-invitation/",
  path: "/accept-invitation/",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DeskTradeLayoutRoute = DeskTradeLayoutRouteImport.update({
  id: "/trade",
  path: "/trade",
  getParentRoute: () => DeskLayoutRoute,
} as any)
const DeskSettingsLayoutRoute = DeskSettingsLayoutRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => DeskLayoutRoute,
} as any)
const DeskPeopleLayoutRoute = DeskPeopleLayoutRouteImport.update({
  id: "/people",
  path: "/people",
  getParentRoute: () => DeskLayoutRoute,
} as any)
const DeskBankingLayoutRoute = DeskBankingLayoutRouteImport.update({
  id: "/banking",
  path: "/banking",
  getParentRoute: () => DeskLayoutRoute,
} as any)
const DeskAccountingLayoutRoute = DeskAccountingLayoutRouteImport.update({
  id: "/accounting",
  path: "/accounting",
  getParentRoute: () => DeskLayoutRoute,
} as any)
const DashboardSuperAdminLayoutRoute =
  DashboardSuperAdminLayoutRouteImport.update({
    id: "/super-admin",
    path: "/super-admin",
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardSettingsLayoutRoute = DashboardSettingsLayoutRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DeskTradeIndexRoute = DeskTradeIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DeskTradeLayoutRoute,
} as any)
const DeskSettingsIndexRoute = DeskSettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DeskSettingsLayoutRoute,
} as any)
const DeskPeopleIndexRoute = DeskPeopleIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DeskPeopleLayoutRoute,
} as any)
const DeskBankingIndexRoute = DeskBankingIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DeskBankingLayoutRoute,
} as any)
const DeskAccountingIndexRoute = DeskAccountingIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DeskAccountingLayoutRoute,
} as any)
const DashboardSuperAdminIndexRoute =
  DashboardSuperAdminIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => DashboardSuperAdminLayoutRoute,
  } as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardSettingsLayoutRoute,
} as any)
const DeskSettingsTaxesRoute = DeskSettingsTaxesRouteImport.update({
  id: "/taxes",
  path: "/taxes",
  getParentRoute: () => DeskSettingsLayoutRoute,
} as any)
const DeskSettingsRolesRoute = DeskSettingsRolesRouteImport.update({
  id: "/roles",
  path: "/roles",
  getParentRoute: () => DeskSettingsLayoutRoute,
} as any)
const DeskSettingsCalendarRoute = DeskSettingsCalendarRouteImport.update({
  id: "/calendar",
  path: "/calendar",
  getParentRoute: () => DeskSettingsLayoutRoute,
} as any)
const DeskPeopleEmployeesRoute = DeskPeopleEmployeesRouteImport.update({
  id: "/employees",
  path: "/employees",
  getParentRoute: () => DeskPeopleLayoutRoute,
} as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: "/security",
    path: "/security",
    getParentRoute: () => DashboardSettingsLayoutRoute,
  } as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: "/api/rpc/$",
  path: "/api/rpc/$",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any)
const DeskTradeSalesIndexRoute = DeskTradeSalesIndexRouteImport.update({
  id: "/sales/",
  path: "/sales/",
  getParentRoute: () => DeskTradeLayoutRoute,
} as any)
const DeskSettingsLocationsIndexRoute =
  DeskSettingsLocationsIndexRouteImport.update({
    id: "/locations/",
    path: "/locations/",
    getParentRoute: () => DeskSettingsLayoutRoute,
  } as any)
const DeskPeopleSuppliersIndexRoute =
  DeskPeopleSuppliersIndexRouteImport.update({
    id: "/suppliers/",
    path: "/suppliers/",
    getParentRoute: () => DeskPeopleLayoutRoute,
  } as any)
const DashboardSuperAdminUsersIndexRoute =
  DashboardSuperAdminUsersIndexRouteImport.update({
    id: "/users/",
    path: "/users/",
    getParentRoute: () => DashboardSuperAdminLayoutRoute,
  } as any)
const DashboardSuperAdminTestEmailIndexRoute =
  DashboardSuperAdminTestEmailIndexRouteImport.update({
    id: "/test-email/",
    path: "/test-email/",
    getParentRoute: () => DashboardSuperAdminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/dashboard": typeof DashboardLayoutRouteWithChildren
  "/desk": typeof DeskLayoutRouteWithChildren
  "/unauthorized": typeof UnauthorizedRoute
  "/dashboard/settings": typeof DashboardSettingsLayoutRouteWithChildren
  "/dashboard/super-admin": typeof DashboardSuperAdminLayoutRouteWithChildren
  "/desk/accounting": typeof DeskAccountingLayoutRouteWithChildren
  "/desk/banking": typeof DeskBankingLayoutRouteWithChildren
  "/desk/people": typeof DeskPeopleLayoutRouteWithChildren
  "/desk/settings": typeof DeskSettingsLayoutRouteWithChildren
  "/desk/trade": typeof DeskTradeLayoutRouteWithChildren
  "/forgot-password": typeof AuthForgotPasswordRoute
  "/login": typeof AuthLoginRoute
  "/register": typeof AuthRegisterRoute
  "/reset-password": typeof AuthResetPasswordRoute
  "/accept-invitation/": typeof AcceptInvitationIndexRoute
  "/dashboard/": typeof DashboardIndexRoute
  "/desk/": typeof DeskIndexRoute
  "/workflow/": typeof WorkflowIndexRoute
  "/api/auth/$": typeof ApiAuthSplatRoute
  "/api/rpc/$": typeof ApiRpcSplatRoute
  "/dashboard/settings/security": typeof DashboardSettingsSecurityRoute
  "/desk/people/employees": typeof DeskPeopleEmployeesRoute
  "/desk/settings/calendar": typeof DeskSettingsCalendarRoute
  "/desk/settings/roles": typeof DeskSettingsRolesRoute
  "/desk/settings/taxes": typeof DeskSettingsTaxesRoute
  "/dashboard/settings/": typeof DashboardSettingsIndexRoute
  "/dashboard/super-admin/": typeof DashboardSuperAdminIndexRoute
  "/desk/accounting/": typeof DeskAccountingIndexRoute
  "/desk/banking/": typeof DeskBankingIndexRoute
  "/desk/people/": typeof DeskPeopleIndexRoute
  "/desk/settings/": typeof DeskSettingsIndexRoute
  "/desk/trade/": typeof DeskTradeIndexRoute
  "/dashboard/super-admin/test-email/": typeof DashboardSuperAdminTestEmailIndexRoute
  "/dashboard/super-admin/users/": typeof DashboardSuperAdminUsersIndexRoute
  "/desk/people/suppliers/": typeof DeskPeopleSuppliersIndexRoute
  "/desk/settings/locations/": typeof DeskSettingsLocationsIndexRoute
  "/desk/trade/sales/": typeof DeskTradeSalesIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/unauthorized": typeof UnauthorizedRoute
  "/forgot-password": typeof AuthForgotPasswordRoute
  "/login": typeof AuthLoginRoute
  "/register": typeof AuthRegisterRoute
  "/reset-password": typeof AuthResetPasswordRoute
  "/accept-invitation": typeof AcceptInvitationIndexRoute
  "/dashboard": typeof DashboardIndexRoute
  "/desk": typeof DeskIndexRoute
  "/workflow": typeof WorkflowIndexRoute
  "/api/auth/$": typeof ApiAuthSplatRoute
  "/api/rpc/$": typeof ApiRpcSplatRoute
  "/dashboard/settings/security": typeof DashboardSettingsSecurityRoute
  "/desk/people/employees": typeof DeskPeopleEmployeesRoute
  "/desk/settings/calendar": typeof DeskSettingsCalendarRoute
  "/desk/settings/roles": typeof DeskSettingsRolesRoute
  "/desk/settings/taxes": typeof DeskSettingsTaxesRoute
  "/dashboard/settings": typeof DashboardSettingsIndexRoute
  "/dashboard/super-admin": typeof DashboardSuperAdminIndexRoute
  "/desk/accounting": typeof DeskAccountingIndexRoute
  "/desk/banking": typeof DeskBankingIndexRoute
  "/desk/people": typeof DeskPeopleIndexRoute
  "/desk/settings": typeof DeskSettingsIndexRoute
  "/desk/trade": typeof DeskTradeIndexRoute
  "/dashboard/super-admin/test-email": typeof DashboardSuperAdminTestEmailIndexRoute
  "/dashboard/super-admin/users": typeof DashboardSuperAdminUsersIndexRoute
  "/desk/people/suppliers": typeof DeskPeopleSuppliersIndexRoute
  "/desk/settings/locations": typeof DeskSettingsLocationsIndexRoute
  "/desk/trade/sales": typeof DeskTradeSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_auth": typeof AuthLayoutRouteWithChildren
  "/dashboard": typeof DashboardLayoutRouteWithChildren
  "/desk": typeof DeskLayoutRouteWithChildren
  "/unauthorized": typeof UnauthorizedRoute
  "/dashboard/settings": typeof DashboardSettingsLayoutRouteWithChildren
  "/dashboard/super-admin": typeof DashboardSuperAdminLayoutRouteWithChildren
  "/desk/accounting": typeof DeskAccountingLayoutRouteWithChildren
  "/desk/banking": typeof DeskBankingLayoutRouteWithChildren
  "/desk/people": typeof DeskPeopleLayoutRouteWithChildren
  "/desk/settings": typeof DeskSettingsLayoutRouteWithChildren
  "/desk/trade": typeof DeskTradeLayoutRouteWithChildren
  "/_auth/forgot-password": typeof AuthForgotPasswordRoute
  "/_auth/login": typeof AuthLoginRoute
  "/_auth/register": typeof AuthRegisterRoute
  "/_auth/reset-password": typeof AuthResetPasswordRoute
  "/accept-invitation/": typeof AcceptInvitationIndexRoute
  "/dashboard/": typeof DashboardIndexRoute
  "/desk/": typeof DeskIndexRoute
  "/workflow/": typeof WorkflowIndexRoute
  "/api/auth/$": typeof ApiAuthSplatRoute
  "/api/rpc/$": typeof ApiRpcSplatRoute
  "/dashboard/settings/security": typeof DashboardSettingsSecurityRoute
  "/desk/people/employees": typeof DeskPeopleEmployeesRoute
  "/desk/settings/calendar": typeof DeskSettingsCalendarRoute
  "/desk/settings/roles": typeof DeskSettingsRolesRoute
  "/desk/settings/taxes": typeof DeskSettingsTaxesRoute
  "/dashboard/settings/": typeof DashboardSettingsIndexRoute
  "/dashboard/super-admin/": typeof DashboardSuperAdminIndexRoute
  "/desk/accounting/": typeof DeskAccountingIndexRoute
  "/desk/banking/": typeof DeskBankingIndexRoute
  "/desk/people/": typeof DeskPeopleIndexRoute
  "/desk/settings/": typeof DeskSettingsIndexRoute
  "/desk/trade/": typeof DeskTradeIndexRoute
  "/dashboard/super-admin/test-email/": typeof DashboardSuperAdminTestEmailIndexRoute
  "/dashboard/super-admin/users/": typeof DashboardSuperAdminUsersIndexRoute
  "/desk/people/suppliers/": typeof DeskPeopleSuppliersIndexRoute
  "/desk/settings/locations/": typeof DeskSettingsLocationsIndexRoute
  "/desk/trade/sales/": typeof DeskTradeSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/dashboard"
    | "/desk"
    | "/unauthorized"
    | "/dashboard/settings"
    | "/dashboard/super-admin"
    | "/desk/accounting"
    | "/desk/banking"
    | "/desk/people"
    | "/desk/settings"
    | "/desk/trade"
    | "/forgot-password"
    | "/login"
    | "/register"
    | "/reset-password"
    | "/accept-invitation/"
    | "/dashboard/"
    | "/desk/"
    | "/workflow/"
    | "/api/auth/$"
    | "/api/rpc/$"
    | "/dashboard/settings/security"
    | "/desk/people/employees"
    | "/desk/settings/calendar"
    | "/desk/settings/roles"
    | "/desk/settings/taxes"
    | "/dashboard/settings/"
    | "/dashboard/super-admin/"
    | "/desk/accounting/"
    | "/desk/banking/"
    | "/desk/people/"
    | "/desk/settings/"
    | "/desk/trade/"
    | "/dashboard/super-admin/test-email/"
    | "/dashboard/super-admin/users/"
    | "/desk/people/suppliers/"
    | "/desk/settings/locations/"
    | "/desk/trade/sales/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/unauthorized"
    | "/forgot-password"
    | "/login"
    | "/register"
    | "/reset-password"
    | "/accept-invitation"
    | "/dashboard"
    | "/desk"
    | "/workflow"
    | "/api/auth/$"
    | "/api/rpc/$"
    | "/dashboard/settings/security"
    | "/desk/people/employees"
    | "/desk/settings/calendar"
    | "/desk/settings/roles"
    | "/desk/settings/taxes"
    | "/dashboard/settings"
    | "/dashboard/super-admin"
    | "/desk/accounting"
    | "/desk/banking"
    | "/desk/people"
    | "/desk/settings"
    | "/desk/trade"
    | "/dashboard/super-admin/test-email"
    | "/dashboard/super-admin/users"
    | "/desk/people/suppliers"
    | "/desk/settings/locations"
    | "/desk/trade/sales"
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/dashboard"
    | "/desk"
    | "/unauthorized"
    | "/dashboard/settings"
    | "/dashboard/super-admin"
    | "/desk/accounting"
    | "/desk/banking"
    | "/desk/people"
    | "/desk/settings"
    | "/desk/trade"
    | "/_auth/forgot-password"
    | "/_auth/login"
    | "/_auth/register"
    | "/_auth/reset-password"
    | "/accept-invitation/"
    | "/dashboard/"
    | "/desk/"
    | "/workflow/"
    | "/api/auth/$"
    | "/api/rpc/$"
    | "/dashboard/settings/security"
    | "/desk/people/employees"
    | "/desk/settings/calendar"
    | "/desk/settings/roles"
    | "/desk/settings/taxes"
    | "/dashboard/settings/"
    | "/dashboard/super-admin/"
    | "/desk/accounting/"
    | "/desk/banking/"
    | "/desk/people/"
    | "/desk/settings/"
    | "/desk/trade/"
    | "/dashboard/super-admin/test-email/"
    | "/dashboard/super-admin/users/"
    | "/desk/people/suppliers/"
    | "/desk/settings/locations/"
    | "/desk/trade/sales/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  DeskLayoutRoute: typeof DeskLayoutRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  AcceptInvitationIndexRoute: typeof AcceptInvitationIndexRoute
  WorkflowIndexRoute: typeof WorkflowIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/unauthorized": {
      id: "/unauthorized"
      path: "/unauthorized"
      fullPath: "/unauthorized"
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/desk": {
      id: "/desk"
      path: "/desk"
      fullPath: "/desk"
      preLoaderRoute: typeof DeskLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboard": {
      id: "/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/workflow/": {
      id: "/workflow/"
      path: "/workflow"
      fullPath: "/workflow/"
      preLoaderRoute: typeof WorkflowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/desk/": {
      id: "/desk/"
      path: "/"
      fullPath: "/desk/"
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskLayoutRoute
    }
    "/dashboard/": {
      id: "/dashboard/"
      path: "/"
      fullPath: "/dashboard/"
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    "/accept-invitation/": {
      id: "/accept-invitation/"
      path: "/accept-invitation"
      fullPath: "/accept-invitation/"
      preLoaderRoute: typeof AcceptInvitationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth/reset-password": {
      id: "/_auth/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    "/_auth/register": {
      id: "/_auth/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    "/_auth/login": {
      id: "/_auth/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    "/_auth/forgot-password": {
      id: "/_auth/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    "/desk/trade": {
      id: "/desk/trade"
      path: "/trade"
      fullPath: "/desk/trade"
      preLoaderRoute: typeof DeskTradeLayoutRouteImport
      parentRoute: typeof DeskLayoutRoute
    }
    "/desk/settings": {
      id: "/desk/settings"
      path: "/settings"
      fullPath: "/desk/settings"
      preLoaderRoute: typeof DeskSettingsLayoutRouteImport
      parentRoute: typeof DeskLayoutRoute
    }
    "/desk/people": {
      id: "/desk/people"
      path: "/people"
      fullPath: "/desk/people"
      preLoaderRoute: typeof DeskPeopleLayoutRouteImport
      parentRoute: typeof DeskLayoutRoute
    }
    "/desk/banking": {
      id: "/desk/banking"
      path: "/banking"
      fullPath: "/desk/banking"
      preLoaderRoute: typeof DeskBankingLayoutRouteImport
      parentRoute: typeof DeskLayoutRoute
    }
    "/desk/accounting": {
      id: "/desk/accounting"
      path: "/accounting"
      fullPath: "/desk/accounting"
      preLoaderRoute: typeof DeskAccountingLayoutRouteImport
      parentRoute: typeof DeskLayoutRoute
    }
    "/dashboard/super-admin": {
      id: "/dashboard/super-admin"
      path: "/super-admin"
      fullPath: "/dashboard/super-admin"
      preLoaderRoute: typeof DashboardSuperAdminLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    "/dashboard/settings": {
      id: "/dashboard/settings"
      path: "/settings"
      fullPath: "/dashboard/settings"
      preLoaderRoute: typeof DashboardSettingsLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    "/desk/trade/": {
      id: "/desk/trade/"
      path: "/"
      fullPath: "/desk/trade/"
      preLoaderRoute: typeof DeskTradeIndexRouteImport
      parentRoute: typeof DeskTradeLayoutRoute
    }
    "/desk/settings/": {
      id: "/desk/settings/"
      path: "/"
      fullPath: "/desk/settings/"
      preLoaderRoute: typeof DeskSettingsIndexRouteImport
      parentRoute: typeof DeskSettingsLayoutRoute
    }
    "/desk/people/": {
      id: "/desk/people/"
      path: "/"
      fullPath: "/desk/people/"
      preLoaderRoute: typeof DeskPeopleIndexRouteImport
      parentRoute: typeof DeskPeopleLayoutRoute
    }
    "/desk/banking/": {
      id: "/desk/banking/"
      path: "/"
      fullPath: "/desk/banking/"
      preLoaderRoute: typeof DeskBankingIndexRouteImport
      parentRoute: typeof DeskBankingLayoutRoute
    }
    "/desk/accounting/": {
      id: "/desk/accounting/"
      path: "/"
      fullPath: "/desk/accounting/"
      preLoaderRoute: typeof DeskAccountingIndexRouteImport
      parentRoute: typeof DeskAccountingLayoutRoute
    }
    "/dashboard/super-admin/": {
      id: "/dashboard/super-admin/"
      path: "/"
      fullPath: "/dashboard/super-admin/"
      preLoaderRoute: typeof DashboardSuperAdminIndexRouteImport
      parentRoute: typeof DashboardSuperAdminLayoutRoute
    }
    "/dashboard/settings/": {
      id: "/dashboard/settings/"
      path: "/"
      fullPath: "/dashboard/settings/"
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsLayoutRoute
    }
    "/desk/settings/taxes": {
      id: "/desk/settings/taxes"
      path: "/taxes"
      fullPath: "/desk/settings/taxes"
      preLoaderRoute: typeof DeskSettingsTaxesRouteImport
      parentRoute: typeof DeskSettingsLayoutRoute
    }
    "/desk/settings/roles": {
      id: "/desk/settings/roles"
      path: "/roles"
      fullPath: "/desk/settings/roles"
      preLoaderRoute: typeof DeskSettingsRolesRouteImport
      parentRoute: typeof DeskSettingsLayoutRoute
    }
    "/desk/settings/calendar": {
      id: "/desk/settings/calendar"
      path: "/calendar"
      fullPath: "/desk/settings/calendar"
      preLoaderRoute: typeof DeskSettingsCalendarRouteImport
      parentRoute: typeof DeskSettingsLayoutRoute
    }
    "/desk/people/employees": {
      id: "/desk/people/employees"
      path: "/employees"
      fullPath: "/desk/people/employees"
      preLoaderRoute: typeof DeskPeopleEmployeesRouteImport
      parentRoute: typeof DeskPeopleLayoutRoute
    }
    "/dashboard/settings/security": {
      id: "/dashboard/settings/security"
      path: "/security"
      fullPath: "/dashboard/settings/security"
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof DashboardSettingsLayoutRoute
    }
    "/api/rpc/$": {
      id: "/api/rpc/$"
      path: "/api/rpc/$"
      fullPath: "/api/rpc/$"
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/auth/$": {
      id: "/api/auth/$"
      path: "/api/auth/$"
      fullPath: "/api/auth/$"
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/desk/trade/sales/": {
      id: "/desk/trade/sales/"
      path: "/sales"
      fullPath: "/desk/trade/sales/"
      preLoaderRoute: typeof DeskTradeSalesIndexRouteImport
      parentRoute: typeof DeskTradeLayoutRoute
    }
    "/desk/settings/locations/": {
      id: "/desk/settings/locations/"
      path: "/locations"
      fullPath: "/desk/settings/locations/"
      preLoaderRoute: typeof DeskSettingsLocationsIndexRouteImport
      parentRoute: typeof DeskSettingsLayoutRoute
    }
    "/desk/people/suppliers/": {
      id: "/desk/people/suppliers/"
      path: "/suppliers"
      fullPath: "/desk/people/suppliers/"
      preLoaderRoute: typeof DeskPeopleSuppliersIndexRouteImport
      parentRoute: typeof DeskPeopleLayoutRoute
    }
    "/dashboard/super-admin/users/": {
      id: "/dashboard/super-admin/users/"
      path: "/users"
      fullPath: "/dashboard/super-admin/users/"
      preLoaderRoute: typeof DashboardSuperAdminUsersIndexRouteImport
      parentRoute: typeof DashboardSuperAdminLayoutRoute
    }
    "/dashboard/super-admin/test-email/": {
      id: "/dashboard/super-admin/test-email/"
      path: "/test-email"
      fullPath: "/dashboard/super-admin/test-email/"
      preLoaderRoute: typeof DashboardSuperAdminTestEmailIndexRouteImport
      parentRoute: typeof DashboardSuperAdminLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface DashboardSettingsLayoutRouteChildren {
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsLayoutRouteChildren: DashboardSettingsLayoutRouteChildren =
  {
    DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
    DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  }

const DashboardSettingsLayoutRouteWithChildren =
  DashboardSettingsLayoutRoute._addFileChildren(
    DashboardSettingsLayoutRouteChildren,
  )

interface DashboardSuperAdminLayoutRouteChildren {
  DashboardSuperAdminIndexRoute: typeof DashboardSuperAdminIndexRoute
  DashboardSuperAdminTestEmailIndexRoute: typeof DashboardSuperAdminTestEmailIndexRoute
  DashboardSuperAdminUsersIndexRoute: typeof DashboardSuperAdminUsersIndexRoute
}

const DashboardSuperAdminLayoutRouteChildren: DashboardSuperAdminLayoutRouteChildren =
  {
    DashboardSuperAdminIndexRoute: DashboardSuperAdminIndexRoute,
    DashboardSuperAdminTestEmailIndexRoute:
      DashboardSuperAdminTestEmailIndexRoute,
    DashboardSuperAdminUsersIndexRoute: DashboardSuperAdminUsersIndexRoute,
  }

const DashboardSuperAdminLayoutRouteWithChildren =
  DashboardSuperAdminLayoutRoute._addFileChildren(
    DashboardSuperAdminLayoutRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardSettingsLayoutRoute: typeof DashboardSettingsLayoutRouteWithChildren
  DashboardSuperAdminLayoutRoute: typeof DashboardSuperAdminLayoutRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardSettingsLayoutRoute: DashboardSettingsLayoutRouteWithChildren,
  DashboardSuperAdminLayoutRoute: DashboardSuperAdminLayoutRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface DeskAccountingLayoutRouteChildren {
  DeskAccountingIndexRoute: typeof DeskAccountingIndexRoute
}

const DeskAccountingLayoutRouteChildren: DeskAccountingLayoutRouteChildren = {
  DeskAccountingIndexRoute: DeskAccountingIndexRoute,
}

const DeskAccountingLayoutRouteWithChildren =
  DeskAccountingLayoutRoute._addFileChildren(DeskAccountingLayoutRouteChildren)

interface DeskBankingLayoutRouteChildren {
  DeskBankingIndexRoute: typeof DeskBankingIndexRoute
}

const DeskBankingLayoutRouteChildren: DeskBankingLayoutRouteChildren = {
  DeskBankingIndexRoute: DeskBankingIndexRoute,
}

const DeskBankingLayoutRouteWithChildren =
  DeskBankingLayoutRoute._addFileChildren(DeskBankingLayoutRouteChildren)

interface DeskPeopleLayoutRouteChildren {
  DeskPeopleEmployeesRoute: typeof DeskPeopleEmployeesRoute
  DeskPeopleIndexRoute: typeof DeskPeopleIndexRoute
  DeskPeopleSuppliersIndexRoute: typeof DeskPeopleSuppliersIndexRoute
}

const DeskPeopleLayoutRouteChildren: DeskPeopleLayoutRouteChildren = {
  DeskPeopleEmployeesRoute: DeskPeopleEmployeesRoute,
  DeskPeopleIndexRoute: DeskPeopleIndexRoute,
  DeskPeopleSuppliersIndexRoute: DeskPeopleSuppliersIndexRoute,
}

const DeskPeopleLayoutRouteWithChildren =
  DeskPeopleLayoutRoute._addFileChildren(DeskPeopleLayoutRouteChildren)

interface DeskSettingsLayoutRouteChildren {
  DeskSettingsCalendarRoute: typeof DeskSettingsCalendarRoute
  DeskSettingsRolesRoute: typeof DeskSettingsRolesRoute
  DeskSettingsTaxesRoute: typeof DeskSettingsTaxesRoute
  DeskSettingsIndexRoute: typeof DeskSettingsIndexRoute
  DeskSettingsLocationsIndexRoute: typeof DeskSettingsLocationsIndexRoute
}

const DeskSettingsLayoutRouteChildren: DeskSettingsLayoutRouteChildren = {
  DeskSettingsCalendarRoute: DeskSettingsCalendarRoute,
  DeskSettingsRolesRoute: DeskSettingsRolesRoute,
  DeskSettingsTaxesRoute: DeskSettingsTaxesRoute,
  DeskSettingsIndexRoute: DeskSettingsIndexRoute,
  DeskSettingsLocationsIndexRoute: DeskSettingsLocationsIndexRoute,
}

const DeskSettingsLayoutRouteWithChildren =
  DeskSettingsLayoutRoute._addFileChildren(DeskSettingsLayoutRouteChildren)

interface DeskTradeLayoutRouteChildren {
  DeskTradeIndexRoute: typeof DeskTradeIndexRoute
  DeskTradeSalesIndexRoute: typeof DeskTradeSalesIndexRoute
}

const DeskTradeLayoutRouteChildren: DeskTradeLayoutRouteChildren = {
  DeskTradeIndexRoute: DeskTradeIndexRoute,
  DeskTradeSalesIndexRoute: DeskTradeSalesIndexRoute,
}

const DeskTradeLayoutRouteWithChildren = DeskTradeLayoutRoute._addFileChildren(
  DeskTradeLayoutRouteChildren,
)

interface DeskLayoutRouteChildren {
  DeskAccountingLayoutRoute: typeof DeskAccountingLayoutRouteWithChildren
  DeskBankingLayoutRoute: typeof DeskBankingLayoutRouteWithChildren
  DeskPeopleLayoutRoute: typeof DeskPeopleLayoutRouteWithChildren
  DeskSettingsLayoutRoute: typeof DeskSettingsLayoutRouteWithChildren
  DeskTradeLayoutRoute: typeof DeskTradeLayoutRouteWithChildren
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskLayoutRouteChildren: DeskLayoutRouteChildren = {
  DeskAccountingLayoutRoute: DeskAccountingLayoutRouteWithChildren,
  DeskBankingLayoutRoute: DeskBankingLayoutRouteWithChildren,
  DeskPeopleLayoutRoute: DeskPeopleLayoutRouteWithChildren,
  DeskSettingsLayoutRoute: DeskSettingsLayoutRouteWithChildren,
  DeskTradeLayoutRoute: DeskTradeLayoutRouteWithChildren,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskLayoutRouteWithChildren = DeskLayoutRoute._addFileChildren(
  DeskLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  DeskLayoutRoute: DeskLayoutRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  AcceptInvitationIndexRoute: AcceptInvitationIndexRoute,
  WorkflowIndexRoute: WorkflowIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
